name: Deploy to Firebase Hosting on PR merge

on:
  push:
    branches:
      - main  # remplace par 'principal' si ta branche Git s'appelle comme ça

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_LE_MAMITA }}"
          channelId: live
          projectId: le-mamita
